version: '3.4'

services:
  job:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 ipe-start.py "]
    ports:
      - 5678:5678
