version: '3.8'

services:
  job:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    environment:
      - IPE_ENV_FILE=/secrets/ipe/.env
    volumes:
      - ${HOME}/secrets:/secrets
  test: 
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    environment:
      - IPE_ENV_FILE=/secrets/ipe/.env
    volumes:
      - ${HOME}/secrets:/secrets
    command: pytest --log-cli-level=INFO